[Avion_1]
; AVION LIGERO
T_aceleracio-En=12000
T_AleronUp=400
T_estabilizar=3000
T_AleronDown=400
T_vuelo=25000
T_AleronUp_aterrizaje=700
T_AleronDown_aterrizaje=800
T_frenado=2500
T_motorOff=10000


[Avion_2]
; AVION MEDIANO
T_aceleracion=20000
T_AleronUp=1500
T_estabilizar=5000
T_AleronDown=800
T_vuelo=40000
T_AleronUp_aterrizaje=1200
T_AleronDown_aterrizaje=1500
T_frenado=4000
T_motorOff=15000


[Avion_3]
; AVION PESADO
T_aceleracion=45000
T_AleronUp=4000
T_estabilizar=8000
T_AleronDown=2500
T_vuelo=60000
T_AleronUp_aterrizaje=3000
T_AleronDown_aterrizaje=3500
T_frenado=7000
T_motorOff=20000